/* Generated By:JavaCC: Do not edit this line. ColorizerConstants.java */
public interface ColorizerConstants {

  int EOF = 0;
  int DIGITS = 2;
  int UPPER = 3;
  int LOWER = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<DIGITS>",
    "<UPPER>",
    "<LOWER>",
  };

}
